<?xml version="1.0"?>
<package format="2">
  <name>winch_control_plugin</name>
  <version>0.0.1</version>
  <description>Winch control Gazebo plugin for tethered drones</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <exec_depend>roscpp</exec_depend>

  <build_export_depend>gazebo</build_export_depend>
  <exec_depend>gazebo</exec_depend>
  
  <build_depend>std_msgs</build_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <gazebo_ros plugin_path="${prefix}/lib" gazebo_media_path="${prefix}"/>
  </export>
</package>

